### ISSUE TITLE
localGetEx doesn't compile to TEAL properly

### ISSUE THREAD

**Issue by haardikk21** [algorand/pyteal#38]
When using `App.localGetEx(Int(1), Global.current_application_id(), Bytes("T1"))` it pops out TEAL similar to `load 1` 

However, the correct and expected output, which comes from using `App.localGet(Int(1), Bytes("T1"))` is 
```
byte "T1"
app_local_get
```

**Comment by jasonpaulos** [comment]
Can you show a small example of how you're using `App.localGetEx`? Since the TEAL op `app_local_get_ex` pushes two values to the stack, `App.localGetEx` behaves a little differently than `App.localGet`. This section has some examples: https://pyteal.readthedocs.io/en/stable/state.html#external-local

**Comment by haardikk21** [comment]
Here's a simplistic example I made up based on code I am facing the issue in:

Note: I am using the latest PyTeal version from Github, not the last release.

```py
#!/usr/bin/env python3

from pyteal import *

def test():
    on_opt_in = Seq([
        App.localPut(Int(0), Bytes("T1"), Int(0)),
        Int(1)
    ])

    t1_val = App.localGetEx(Int(1), Global.current_application_id(), Bytes("T1"))

    on_function = Seq(
        [Assert(
            And(
                Txn.accounts.length() == Int(1),
                t1_val.hasValue(),
                t1_val.value() == Btoi(Txn.application_args[0])
            )
        ),
        Int(1)
    ])
    
    program = Cond(
        [Txn.on_completion() == OnComplete.OptIn,on_opt_in],
        [Txn.on_completion() == OnComplete.NoOp, on_function]
    )
    return program


if __name__ == "__main__":
    print(compileTeal(test(), Mode.Application))
```

This prints the following:

```
#pragma version 2
txn OnCompletion
int OptIn
==
bnz l6
txn OnCompletion
int NoOp
==
bnz l3
err
l3:
txn NumAccounts
int 1
==
load 0
&&
load 1
txna ApplicationArgs 0
btoi
==
&&
bnz l5
err
l5:
int 1
b l7
l6:
int 0
byte "T1"
int 0
app_local_put
int 1
l7:
```

**Comment by haardikk21** [comment]
The same code with `App.localGetEx(Int(1), Global.current_application_id(), Bytes("T1"))` when replaced with `App.localGet(Int(1), Bytes("T1"))` returns the following TEAL

```
#pragma version 2
txn OnCompletion
int OptIn
==
bnz l6
txn OnCompletion
int NoOp
==
bnz l3
err
l3:
txn NumAccounts
int 1
==
int 1
byte "T1"
app_local_get
txna ApplicationArgs 0
btoi
==
&&
bnz l5
err
l5:
int 1
b l7
l6:
int 0
byte "T1"
int 0
app_local_put
int 1
l7:
```

**Comment by jasonpaulos** [comment]
From [the documentation](https://pyteal.readthedocs.io/en/stable/state.html#external-state):

> Note: Even though the MaybeValue returned by App.globalGetEx and App.localGetEx cannot be used directly, it must be included in the application before hasValue() and value() are called on it. You will probably want to use Seq to do this.

Meaning before using the returned value from `App.localGetEx`, you need to include it in your program. Unfortunately this is pretty subtle and easy to miss, which is why I created #35 which would have the compiler raise an error if you try to use the result of `App.localGetEx` (or any other expression that returns a `MaybeValue`) without including it first.

This would be the correct way to use the expression (note that `t1_val` is included in the body of the `Seq`):

```python
#!/usr/bin/env python3

from pyteal import *

def test():
    on_opt_in = Seq([
        App.localPut(Int(0), Bytes("T1"), Int(0)),
        Int(1)
    ])

    t1_val = App.localGetEx(Int(1), Global.current_application_id(), Bytes("T1"))

    on_function = Seq([
        t1_val,
        Assert(
            And(
                Txn.accounts.length() == Int(1),
                t1_val.hasValue(),
                t1_val.value() == Btoi(Txn.application_args[0])
            )
        ),
        Int(1)
    ])
    
    program = Cond(
        [Txn.on_completion() == OnComplete.OptIn,on_opt_in],
        [Txn.on_completion() == OnComplete.NoOp, on_function]
    )
    return program


if __name__ == "__main__":
    print(compileTeal(test(), Mode.Application))

```

**Comment by haardikk21** [comment]
Ah interesting - yeah the docs aren't very clear about that, thanks for clearing it up!
