### ISSUE TITLE
Get current contract address

### ISSUE THREAD

**Issue by Lumene98** [algorand/pyteal#44]
Is there a way to get the current address of the contract from pyteal? If there's not I think it would be a pretty useful feature to have

**Comment by jasonpaulos** [comment]
For a LogicSig contract, `Txn.sender()` will be the address of the contract, with one exception.

The one situation in which `Txn.sender()` will not be the contract's address is if another account, let's say account `B`, rekeys to the contract address. Then a transaction could originate from account `B`, but the LogicSig is responsible for verifying it, so `Txn.sender()` will be the address of `B`.

In most cases you can probably ignore this though, since if your program approves the transaction, it affects the account `B`, not your program's account.

**Comment by jasonpaulos** [comment]
When a transaction sends funds or assets to a LogicSig account, the LogicSig program does not execute at all. The program only executes when a transaction originates from its address. I hope that helps!

**Comment by Lumene98** [comment]
Oh sorry! I'm still fairly new at this concepts, this really helps!
