### ISSUE TITLE
Ensure setup.py project version is bumped during releases

### ISSUE THREAD

**Issue by michaeldiamant** [algorand/pyteal#595]
## Problem

On several occasions, we've unintentionally created an unusable git release tag by forgetting to bump the project version in `setup.py`.  In such situations, we need to issue a new git tag + Github release to fix the problem.

Here's an example of a PR fixing a missed `setup.py` version bump during the v0.20.0 release:  https://github.com/algorand/pyteal/pull/591/files#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L10.

Based on group discussion to find low-to-moderate cost options, the story requests these changes:
* Add a release checklist to the repo (e.g. `releasing.md` or similar).  The checklist codifies the release steps as a way to reduce the chance for _any_ error.
* Add a test comparing the `setup.py` project version with the latest version header in https://github.com/algorand/pyteal/blob/master/CHANGELOG.md.  
  * Excluding unreleased changes, the version _should_ always match `setup.py`.
  * Here's an example PR creating during a release updating `CHANGELOG.md`:  https://github.com/algorand/pyteal/pull/582/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3.

**Comment by algochoi** [comment]
This PR: https://github.com/algorand/pyteal/pull/637 introduced a [new checklist for releasing PyTeal](https://github.com/algorand/pyteal/blob/master/release-process.md). This issue looks okay to resolve, since the [Github Action to upload to PyPi](https://github.com/algorand/pyteal/actions/runs/3387261940/jobs/5627959460) will fail if the `setup.py` version is not bumped, and the checklist mentions to check that the workflow output is correct.
